<?php if ($this->getCurrencyCount() >= 1): ?>
    <select class="right select-black" name="currency" onchange="setLocation(this.value)">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if ($_code == $this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                <?php echo $_name ?> – <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php

endif;